
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMA DIRECTION DOT EQUALS EQUALS FLOAT ID INT LCURLYB LEVEL LIST LPAREN METHOD METHOD_1P METHOD_2P METHOD_NO METHOD_NP RCURLYB RPAREN STRING STRINGassignment : ID '=' ID"
    
_lr_action_items = {'ID':([0,3,],[2,4,]),'$end':([1,4,],[0,-1,]),'=':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assignment","S'",1,None,None,None),
  ('assignment -> ID = ID','assignment',3,'p_img_assignment','sip_parser.py',16),
]
